project:
  type: website
  output-dir: docs

website:
  title: "Nico Giordano"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - research.qmd

format:
  html:
    theme: united
    mainfont: arial
    fontsize: 1.0rem
    fontcolor: "#045720"
    linkcolor: "#690acf"
    monofont: courier new
    css: styles.css
    toc: true



