project:
  type: website
  output-dir: docs

website:
  title: "Nico Giordano"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
        text: About
      - research.qmd
        text: Research

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



